Repository kpuce2022CD/hummingbird, pull requests merged in 2022-05, with the labels that each got.

#73 장바구니 수량 더하기 빼기 및 장바구니 삭제 기능 구현
  frontend/components/AdminMenu/AdminMenu.tsx
  frontend/components/AdminMenu/style.tsx
  frontend/components/Banner.tsx
  frontend/components/CartItem/CartItem.tsx
  frontend/components/CartItem/style.tsx
  frontend/components/FoodCard/FoodCard.tsx
  frontend/components/FoodCard/style.tsx
  frontend/components/FoodMenuItem/FoodMenuItem.tsx
  frontend/components/MenuCard/style.tsx
  frontend/components/MenuModal/MenuUpdateForm.tsx
  frontend/pages/paypage.tsx
Labels: duplicate

#75 로그인 페이지 프론트 구현
  frontend/components/Login.tsx
  frontend/pages/loginpage.tsx
Labels: enhancement

#79 주문 내역건 조회 페이지 마크업
  data.json
  frontend/components/OrderPage/Item.tsx/Item.style.ts
  frontend/components/OrderPage/Item.tsx/Item.tsx
  frontend/components/OrderPage/Item.tsx/index.ts
  frontend/components/OrderPage/OrderInfoBtn/OrderInfo.tsx
  frontend/components/OrderPage/OrderInfoBtn/OrferInfo.style.ts
  frontend/components/OrderPage/OrderInfoBtn/index.ts
  frontend/components/OrderPage/OrderList/OrderList.style.ts
  frontend/components/OrderPage/OrderList/OrderList.tsx
  frontend/components/OrderPage/OrderList/index.ts
  frontend/components/OrderPage/OrderTap/OrderTap.style.ts
  frontend/components/OrderPage/OrderTap/OrderTap.tsx
  frontend/components/OrderPage/OrderTap/index.ts
  frontend/components/PayBtn/PayBtn.tsx
  frontend/data/IOrderInfo.ts
  frontend/data/getOrderInfo.ts
  frontend/data/index.ts
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
  frontend/pages/index.tsx
  frontend/pages/orderpage.tsx
  frontend/pages/qrpage.tsx
  frontend/pages/resultmenu.tsx
  frontend/utils/useAsync.ts
Labels: duplicate, enhancement

#80 매출 조회
  backend/build.gradle
  backend/src/main/java/com/hummingbird/backend/order/controller/OrderController.java
  backend/src/main/java/com/hummingbird/backend/order/dto/request/SalesCreateRequest.java
  backend/src/main/java/com/hummingbird/backend/order/dto/response/SalesCreateResponse.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderRepository.java
  backend/src/main/java/com/hummingbird/backend/order/service/OrderService.java
Labels: enhancement

#81 QR 코드 테이블 갯수만큼 생성 및 저장, OrderPage 일부 내용 변경
  data.json
  frontend/components/ExViewPhone/ExViewPhone.tsx
  frontend/components/OrderPage/Item.tsx/Item.tsx
  frontend/components/OrderPage/OrderBtn/OrderBtn.style.ts
  frontend/components/OrderPage/OrderBtn/OrderBtn.tsx
  frontend/components/OrderPage/OrderBtn/index.ts
  frontend/components/OrderPage/OrderInfoBtn/OrderInfo.tsx
  frontend/components/OrderPage/OrderInfoBtn/OrferInfo.style.ts
  frontend/components/OrderPage/OrderInfoBtn/index.ts
  frontend/components/OrderPage/OrderList/OrderList.tsx
  frontend/components/QrPage/QrList/QrList.style.ts
  frontend/components/QrPage/QrList/QrList.tsx
  frontend/components/QrPage/QrList/index.ts
  frontend/components/QrPage/QrModal/QrModal.style.ts
  frontend/components/QrPage/QrModal/QrModal.tsx
  frontend/components/QrPage/QrModal/index.ts
  frontend/pages/qrpage.tsx
  frontend/utils/onImageDownload.ts
  menu-canvas/files/c5bd4c121ab9cd055f7d2fcaeb1c3b03coffee.jpeg
Labels: duplicate, enhancement

#84 orderItem api
  backend/src/main/java/com/hummingbird/backend/order/controller/OrderController.java
  backend/src/main/java/com/hummingbird/backend/order/domain/OrderItem.java
  backend/src/main/java/com/hummingbird/backend/order/dto/OrderItemBillInfo.java
  backend/src/main/java/com/hummingbird/backend/order/dto/response/OrderItemBillResponse.java
  backend/src/main/java/com/hummingbird/backend/order/dto/response/OrderItemStatusResponse.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderItemRepository.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderRepository.java
  backend/src/main/java/com/hummingbird/backend/order/service/OrderService.java
Labels: enhancement

#88 로그인 및 회원가입 구현
  frontend/components/Banner.tsx
  frontend/components/Btn/LoginBtn/LoginBtn.tsx
  frontend/components/Btn/SignUpBtn/SignUpBtn.tsx
  frontend/components/Login.tsx
  frontend/components/Login/Login.tsx
  frontend/components/Login/index.tsx
  frontend/components/Login/style.tsx
  frontend/components/SignUpPage/SignUpForm/SignUpForm.style.ts
  frontend/components/SignUpPage/SignUpForm/SignUpForm.tsx
  frontend/components/SignUpPage/SignUpForm/index.ts
  frontend/data/getOrderInfo.ts
  frontend/package.json
  frontend/pages/signup.tsx
  frontend/utils/handleFormInputChange.ts
  frontend/utils/index.ts
  frontend/utils/useFetchData.ts
Labels: documentation, enhancement

#90 로그인 API 와이들드 카드 제거 및 Credentials 설정
  frontend/components/Login.tsx
Labels: documentation, enhancement

#95 feat : 로그아웃 라우팅 설정
  frontend/components/LoginPage/LoginForm/LoginForm.style.ts
  frontend/components/MyPage/MyMenuList/intex.ts
Labels: duplicate

#99 결제 시 QR코드 내 테이블 번호와 OwnerId가 담겨 결제되도록 수정
  frontend/components/CartModal/CartModal.tsx
  frontend/components/MenuCard/MenuCard.tsx
  frontend/components/MyPage/MyPageSideMenu/MyPageSideMenu.tsx
  frontend/components/OrderPage/Item.tsx/Item.style.ts
  frontend/components/OrderPage/Item.tsx/Item.tsx
  frontend/components/OrderPage/OrderList/OrderList.style.ts
  frontend/components/OrderPage/OrderList/OrderList.tsx
  frontend/components/PayBtn/PayBtn.tsx
  frontend/components/QrPage/QrList/QrList.tsx
  frontend/data/IOrderInfo.ts
  frontend/data/getOrderInfo.ts
  frontend/pages/orderpage/[ownerid].tsx
  frontend/pages/qrpage.tsx
  frontend/pages/resultmenu.tsx
  frontend/utils/index.ts
  frontend/utils/onImageDownload.ts
  frontend/utils/useFetchData.ts
  menu-canvas/files/0b630da84a988950e7e7d56647602d8dFrame_5007.png
Labels: enhancement

#101 어드민 페이지 구현
  frontend/components/AdminPage/AdminTable/AdminTable.style.ts
  frontend/components/AdminPage/AdminTable/AdminTable.tsx
  frontend/components/AdminPage/AdminTable/index.ts
  frontend/components/FoodCard/FoodCard.tsx
  frontend/components/LoginPage/LoginForm/LoginForm.tsx
  frontend/components/MenuCard/MenuCard.tsx
  frontend/components/MenuInfo/MenuInfo.tsx
  frontend/components/MenuModal/MenuAddForm.tsx
  frontend/components/MenuModal/MenuUpdateForm.tsx
  frontend/components/MenuPreContent/MenuPreContent.tsx
  frontend/components/OrderPage/OrderList/OrderList.tsx
  frontend/components/OrderPage/OrderTap/OrderTap.tsx
  frontend/components/PayBtn/PayBtn.tsx
  frontend/components/QrPage/QrList/QrList.tsx
  frontend/data/IOrderInfo.ts
  frontend/data/getOrderInfo.ts
  frontend/data/getOwnerInfo.ts
  frontend/data/index.ts
  frontend/pages/admin.tsx
  frontend/pages/menupage/[menuid].tsx
  frontend/utils/index.ts
  frontend/utils/useFetchData.ts
  menu-canvas/files/11c589abf00433bd2f2108d929508fbfCMC.png
Labels: enhancement

#103 미디어쿼리 적용
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/workspace.xml
  backend/build.gradle
  backend/src/main/java/com/hummingbird/backend/common/config/security/filter/OwnerLoginProcessingFilter.java
  backend/src/main/java/com/hummingbird/backend/order/controller/OrderController.java
  backend/src/main/java/com/hummingbird/backend/order/domain/OrderItem.java
  backend/src/main/java/com/hummingbird/backend/order/dto/OrderItemBillInfo.java
  backend/src/main/java/com/hummingbird/backend/order/dto/response/OrderItemBillResponse.java
  backend/src/main/java/com/hummingbird/backend/order/dto/response/OrderItemStatusResponse.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderItemRepository.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderRepository.java
  backend/src/main/java/com/hummingbird/backend/order/service/OrderService.java
  backend/src/main/java/com/hummingbird/backend/owner/controller/OwnerController.java
  backend/src/main/java/com/hummingbird/backend/owner/domain/Owner.java
  backend/src/main/java/com/hummingbird/backend/owner/dto/OwnerProfileDto.java
  backend/src/main/java/com/hummingbird/backend/owner/service/OwnerProfileService.java
  backend/src/main/java/com/hummingbird/backend/owner/util/OwnerUtil.java
  frontend/components/Banner.tsx
  frontend/components/ExViewPhone/ExViewPhone.tsx
  frontend/components/Info.tsx
  frontend/components/Nav.tsx
  frontend/pages/qrpage.tsx
  frontend/styles/global-style.tsx
Labels: enhancement

#106 orderItem 조회 API date 옵션 추가
  backend/src/main/java/com/hummingbird/backend/order/controller/OrderController.java
  backend/src/main/java/com/hummingbird/backend/order/repository/OrderItemRepository.java
  backend/src/main/java/com/hummingbird/backend/order/service/OrderService.java
Labels: enhancement
