Repository kpuce2022CD/hummingbird, pull requests merged in 2022-04, with the labels that each got.

#38 CORS 에러 확인을 위한 카테고리 추가 컴포넌트
  frontend/components/MenuModal/MenuModal.tsx
  frontend/components/MenuModal/style.tsx
  frontend/pages/menupage.tsx
Labels: bug, help wanted

#43 prerender 동적 라우팅 제거로 인한 MOCKJson 추가
  frontend/package-lock.json
  frontend/pages/menupage.tsx
Labels: bug

#44 사장님id를 통해 메뉴판 불러오기 CORS 에러
  frontend/components/AdminMenu/AdminMenu.tsx
  frontend/components/AdminMenu/intex.ts
  frontend/components/AdminMenu/style.tsx
  frontend/components/Banner.tsx
  frontend/components/EditPlusBtn/EditPlusBtn.tsx
  frontend/components/EditPlusBtn/index.ts
  frontend/components/MenuList.tsx
  frontend/components/MenuModal/MenuModal.tsx
  frontend/components/MenuModal/index.ts
  frontend/pages/menupage.tsx
  frontend/pages/mypage.tsx
  frontend/pages/mypage/[ownerid].tsx
Labels: bug, duplicate, enhancement

#52 랜딩페이지, 큐알 생성 페이지 스타일 적용
  .github/ISSUE_TEMPLATE/bug_report.md
  frontend/components/Banner.tsx
  frontend/components/FooterBanner.tsx
  frontend/components/Info.tsx
  frontend/components/Nav.tsx
  frontend/pages/index.tsx
  frontend/pages/qrpage.tsx
  frontend/public/img/BannerPic.svg
  frontend/public/img/FooterBanner.svg
  frontend/public/img/GroupPhone.svg
  frontend/public/img/info/Payment.svg
  frontend/public/img/info/checkMac.svg
  frontend/public/img/info/easyMenu.svg
  frontend/public/img/info/easyMenu2.svg
  frontend/styles/global-style.ts
  frontend/styles/styled.d.ts
  frontend/styles/theme.ts
Labels: duplicate, enhancement

#53 마이페이지에서 메뉴판을 확인, 생성, 수정, 삭제 할 수 있도록 구현
  frontend/components/AdminMenu/AdminMenu.tsx
  frontend/components/AdminMenu/style.tsx
  frontend/components/Banner.tsx
  frontend/components/FooterBanner.tsx
  frontend/components/Info.tsx
  frontend/components/MenuCard/MenuCard.tsx
  frontend/components/MenuCard/index.tsx
  frontend/components/MenuCard/style.tsx
  frontend/components/MenuModal/MenuModal.tsx
  frontend/components/MenuModal/style.tsx
  frontend/pages/menupage.tsx
  frontend/pages/mypage.tsx
  frontend/pages/mypage/[ownerid].tsx
  frontend/pages/qrpage.tsx
  frontend/styles/global-style.ts
  frontend/styles/styled.d.ts
  frontend/styles/theme.ts
Labels: bug, duplicate, enhancement

#61 사장님 메뉴판 생성 페이지 구현
  frontend/components/MenuCard/MenuCard.tsx
  frontend/components/MenuFormCard.tsx
  frontend/components/MenuInfo/MenuInfo.tsx
  frontend/components/MenuInfo/style.tsx
  frontend/components/MenuModal/MenuModal.tsx
  frontend/components/MenuModal/MenuUpdateForm.tsx
  frontend/components/MenuModal/index.ts
  frontend/components/MenuPreContent/MenuPreContent.tsx
  frontend/components/MenuPreContent/index.tsx
  frontend/components/MenuPreContent/style.tsx
  frontend/pages/menupage/[menuid].tsx
  frontend/pages/resultmenu.tsx
  frontend/recoil/states.ts
  frontend/utils/numberFormat.ts
Labels: duplicate, enhancement

#64 이미지 업로드 및 불러오기
  backend/src/main/java/com/hummingbird/backend/common/config/WebConfig.java
  backend/src/main/java/com/hummingbird/backend/food/service/serviceImpl/FoodServiceImpl.java
  docker-compose.yml
Labels: bug

#69 프론트 스타일 적용 완료
  frontend/components/Banner.tsx
  frontend/components/Btn/LoginBtn/LoginBtn.tsx
  frontend/components/Btn/LoginBtn/index.ts
  frontend/components/Btn/SignUpBtn/SignUpBtn.tsx
  frontend/components/Btn/SignUpBtn/index.ts
  frontend/components/Desc/StyledItem/StyledItem.tsx
  frontend/components/Desc/StyledItem/index.ts
  frontend/components/ExViewPhone/ExViewPhone.tsx
  frontend/components/ExViewPhone/index.ts
  frontend/components/Footer.tsx
  frontend/components/FooterBanner.tsx
  frontend/components/Info.tsx
  frontend/components/Nav.tsx
  frontend/components/StyledTwoPhone/StyledTwoPhone.tsx
  frontend/components/StyledTwoPhone/index.ts
  frontend/pages/index.tsx
  frontend/pages/qrpage.tsx
  frontend/public/img/QR/QRiPhone.svg
  frontend/public/img/logo.svg
  frontend/public/img/nav_logo.svg
  frontend/public/img/red_bell.svg
Labels: enhancement
